In [7]:
df=pd.read_csv("Environmental_Impact_dataset.csv")

In [8]:
df

       Year  ... Environmental_Growth
0      2016  ...                  NaN
1      2010  ...                  NaN
2      2011  ...            33.333333
3      2012  ...            -6.250000
4      2010  ...                  NaN
...     ...  ...                  ...
14510  2018  ...             2.380952
14511  2019  ...            18.604651
14512  2019  ...                  NaN
14513  2019  ...                  NaN
14514  2019  ...                  NaN

[14515 rows x 9 columns]

In [9]:
gp=df.groupby(['Industry(Exiobase)','Year'])['Env_intensity'].mean().reset_index()
gp.rename(columns={'Env_intensity': 'Ind_Yearavg'}, inplace=True)
gp

                                    Industry(Exiobase)  Year  Ind_Yearavg
0     Activities auxiliary to financial intermediat...  2010    -0.004490
1     Activities auxiliary to financial intermediat...  2011    -0.006840
2     Activities auxiliary to financial intermediat...  2012    -0.005138
3     Activities auxiliary to financial intermediat...  2013    -0.004894
4     Activities auxiliary to financial intermediat...  2014    -0.004938
..                                                 ...   ...          ...
573                             Transport via railways  2019    -0.031467
574  Wholesale trade and commission trade, except o...  2016    -0.006500
575  Wholesale trade and commission trade, except o...  2017    -0.016967
576  Wholesale trade and commission trade, except o...  2018    -0.018417
577  Wholesale trade and commission trade, except o...  2019    -0.005100

[578 rows x 3 columns]

In [24]:
dfo = pd.merge(df, gp, how="outer", on=["Industry(Exiobase)", "Year"])
dfo.head(3)

   Year                     CompanyName  ... Environmental_Growth Ind_Yearavg
0  2016               1&1 DRILLISCH AG   ...                  NaN    -0.01164
1  2016                AFK SISTEMA PAO   ...             6.722107    -0.01164
2  2016   AMERICA MOVIL S.A.B. DE C.V.   ...            13.274336    -0.01164

[3 rows x 10 columns]

In [22]:
from google.colab import files
dfo.to_csv('Environmental_Impact_dataset1.csv') 
files.download('Environmental_Impact_dataset1.csv')